version: '3'
services:
  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - API_KEY=$API_KEY
      - ADMIN_CHAT_ID=$ADMIN_CHAT_ID
    depends_on:
      - wkhtmltopdf
  wkhtmltopdf:
    image: traumfewo/docker-wkhtmltopdf-aas:v1.1.0
    environment:
      - USER=gooduser
      - PASS=secretpassword
    ports:
      - "5552:5555"
    volumes:
      - ./img/logo.png:/app/img/logo.png
