name: Deploy Docker Compose

on:
  push:
    branches:
      - main  # Запускать workflow при пушах в ветку main

jobs:
  deploy:
    runs-on: self-hosted  # Используем ваш собственный GitHub Runner
    steps:
      # Проверка кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Построение образов и запуск контейнеров
      - name: Deploy with Docker Compose
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
        run: |
          echo "API_KEY=$API_KEY" >> .env
          echo "ADMIN_CHAT_ID=$ADMIN_CHAT_ID" >> .env
          echo "API_KEY_DEV" >> .env
          docker-compose down
          docker-compose up -d --build
